// Code generated by ogen, DO NOT EDIT.
package api

type FinancialDataV2AccountsIDBalancesGetRes interface {
	financialDataV2AccountsIDBalancesGetRes()
}

type FinancialDataV2EntitiesGetRes interface {
	financialDataV2EntitiesGetRes()
}

type FinancialDataV2EntitiesIDDeleteRes interface {
	financialDataV2EntitiesIDDeleteRes()
}

type FinancialDataV2EntitiesIDGetRes interface {
	financialDataV2EntitiesIDGetRes()
}

type FinancialDataV2EntitiesPostRes interface {
	financialDataV2EntitiesPostRes()
}

type FinancialDataV2PendingTransactionsIDEventsGetRes interface {
	financialDataV2PendingTransactionsIDEventsGetRes()
}

type IamV2betaOAuth2TokenPostRes interface {
	iamV2betaOAuth2TokenPostRes()
}

type PaymentsV2CounterpartiesIDDeleteRes interface {
	paymentsV2CounterpartiesIDDeleteRes()
}

type PaymentsV2CreditTransferBatchesIDApprovePostRes interface {
	paymentsV2CreditTransferBatchesIDApprovePostRes()
}

type PaymentsV2CreditTransferBatchesIDRejectPostRes interface {
	paymentsV2CreditTransferBatchesIDRejectPostRes()
}

type PaymentsV2CreditTransfersIDEventsGetRes interface {
	paymentsV2CreditTransfersIDEventsGetRes()
}

type PaymentsV2DirectDebitsIDEventsGetRes interface {
	paymentsV2DirectDebitsIDEventsGetRes()
}

type PaymentsV2ExternalAccountsIDDeleteRes interface {
	paymentsV2ExternalAccountsIDDeleteRes()
}

type PaymentsV2MandatesIDEventsGetRes interface {
	paymentsV2MandatesIDEventsGetRes()
}

type PaymentsV2betaCreditTransferBatchesGetRes interface {
	paymentsV2betaCreditTransferBatchesGetRes()
}

type PaymentsV2betaCreditTransferBatchesIDGetRes interface {
	paymentsV2betaCreditTransferBatchesIDGetRes()
}

type PaymentsV2betaCreditTransferBatchesIDResultsGetRes interface {
	paymentsV2betaCreditTransferBatchesIDResultsGetRes()
}

type PaymentsV2betaCreditTransferBatchesPostRes interface {
	paymentsV2betaCreditTransferBatchesPostRes()
}
