{
  "openapi": "3.1.0",
  "info": {
    "title": "Atlar API (v2)",
    "description": "Atlar API (v2)",
    "version": "0.1",
    "contact": {
      "email": "support@atlar.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.txt"
    }
  },
  "servers": [
    {
      "url": "https://api.atlar.com"
    }
  ],
  "tags": [
    {
      "name": "Credit Transfers",
      "description": "Credit transfers are payments initiated by a debtor to transfer funds to a creditor's account.",
      "x-displayName": "Credit Transfers"
    },
    {
      "name": "Direct Debits",
      "description": "Direct debits are payments initiated by a creditor to collect funds from a debtor's account.",
      "x-displayName": "Direct Debits"
    },
    {
      "name": "External Accounts",
      "description": "External accounts are financial accounts held by counterparties at financial institutions.",
      "x-displayName": "External Accounts"
    },
    {
      "name": "Counterparties",
      "description": "Counterparties are entities that the account holder has a relationship with.",
      "x-displayName": "Counterparties"
    },
    {
      "name": "Mandates",
      "description": "Mandates are authorizations given by a debtor to a creditor to collect funds from the account.",
      "x-displayName": "Mandates"
    },
    {
      "name": "Events (webhooks)",
      "description": "Webhooks are automated notifications sent to a specified URL in response to events or changes.",
      "x-displayName": "Events (webhooks)"
    },
    {
      "name": "Accounts",
      "description": "Accounts are financial accounts held by your organization.",
      "x-displayName": "Accounts"
    },
    {
      "name": "Transactions",
      "description": "Transactions are movements of funds that have been booked on an account.",
      "x-displayName": "Transactions"
    },
    {
      "name": "Pending Transactions",
      "description": "Pending transactions are indications of movement of funds that may be booked on an account.",
      "x-displayName": "Pending Transactions"
    },
    {
      "name": "Entities",
      "description": "Entities are legal entities, e.g. companies.",
      "x-displayName": "Entities"
    },
    {
      "name": "OAuth",
      "description": "OAuth 2.0 endpoints.",
      "x-displayName": "OAuth"
    }
  ],
  "paths": {
    "/payments/v2/credit-transfers": {
      "post": {
        "summary": "Create credit transfer",
        "description": "Create a credit transfer payment.",
        "tags": [
          "Credit Transfers"
        ],
        "security": [
          {
            "basicAuth": [
              "credit_transfers:create",
              "accounts:read",
              "entities:read",
              "external_accounts:read",
              "counterparties:read"
            ]
          }
        ]
      },
      "get": {
        "summary": "List credit transfers",
        "description": "Returns a list of credit transfers. Sort order is always descending on date.",
        "tags": [
          "Credit Transfers"
        ],
        "security": [
          {
            "basicAuth": [
              "credit_transfers:read"
            ]
          }
        ]
      }
    },
    "/payments/v2/credit-transfers/{id}": {
      "get": {
        "summary": "Get credit transfer",
        "description": "Retrieve a specific credit transfer.",
        "tags": [
          "Credit Transfers"
        ],
        "security": [
          {
            "basicAuth": [
              "credit_transfers:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update credit transfer",
        "description": "Update a credit transfer.\n\nThe credit transfer execution date can only be changed if the\ncredit transfer has not been scheduled for submission yet.",
        "tags": [
          "Credit Transfers"
        ],
        "security": [
          {
            "basicAuth": [
              "credit_transfers:update"
            ]
          }
        ]
      }
    },
    "/payments/v2/credit-transfers/{id}/events": {
      "get": {
        "summary": "List credit transfer events",
        "description": "Retrieve events for a specific credit transfer. Returns a list of events. For further details on Pagination, see the section above.",
        "tags": [
          "Credit Transfers"
        ],
        "security": [
          {
            "basicAuth": [
              "credit_transfers:read"
            ]
          }
        ]
      }
    },
    "/payments/v2/credit-transfers/{id}:approve": {
      "post": {
        "summary": "Approve credit transfer",
        "description": "Approve the specified credit transfer.",
        "tags": [
          "Credit Transfers"
        ],
        "security": [
          {
            "basicAuth": [
              "credit_transfers:update"
            ]
          }
        ]
      }
    },
    "/payments/v2/credit-transfers/{id}:reject": {
      "post": {
        "summary": "Reject credit transfer",
        "description": "Reject the specified credit transfer.",
        "tags": [
          "Credit Transfers"
        ],
        "security": [
          {
            "basicAuth": [
              "credit_transfers:update"
            ]
          }
        ]
      }
    },
    "/payments/v2beta/credit-transfer-batches": {
      "post": {
        "summary": "Create credit transfer batch",
        "description": "Create a batch of credit transfer payments.\n\nSee https://docs.atlar.com/docs/batch-payments for more information.",
        "tags": [
          "Credit Transfers"
        ],
        "security": [
          {
            "basicAuth": [
              "credit_transfers:create",
              "accounts:read",
              "external_accounts:read",
              "counterparties:read"
            ]
          }
        ]
      },
      "get": {
        "summary": "List credit transfer batches",
        "description": "Returns a list of credit transfer batches.",
        "tags": [
          "Credit Transfers"
        ],
        "security": [
          {
            "basicAuth": [
              "credit_transfers:read"
            ]
          }
        ]
      }
    },
    "/payments/v2beta/credit-transfer-batches/{id}": {
      "get": {
        "summary": "Get credit transfer batch",
        "description": "Retrieve a specific credit transfer batch.",
        "tags": [
          "Credit Transfers"
        ],
        "security": [
          {
            "basicAuth": []
          }
        ]
      }
    },
    "/payments/v2beta/credit-transfer-batches/{id}/results": {
      "get": {
        "summary": "List credit transfer batch results",
        "description": "List processing results for individual credit transfer requests that were part of a credit transfer batch.\nThe result items represent the result(s) of processing the batch request input but doesn't <b>not</b> represent the end-to-end processing of the payment.",
        "tags": [
          "Credit Transfers"
        ],
        "security": [
          {
            "basicAuth": []
          }
        ]
      }
    },
    "/payments/v2/credit-transfer-batches/{id}:approve": {
      "post": {
        "summary": "Approve credit transfer batch",
        "description": "Approve the batch of credit transfers.\n\nApproval of a batch is only applicable when the batch `treatment` is `BATCH`.",
        "tags": [
          "Credit Transfers"
        ],
        "security": [
          {
            "basicAuth": [
              "credit_transfers:update"
            ]
          }
        ]
      }
    },
    "/payments/v2/credit-transfer-batches/{id}:reject": {
      "post": {
        "summary": "Reject credit transfer batch",
        "description": "Reject the batch of credit transfers.\n\nRejection of a batch is only applicable when the batch `treatment` is `BATCH`.",
        "tags": [
          "Credit Transfers"
        ],
        "security": [
          {
            "basicAuth": [
              "credit_transfers:update"
            ]
          }
        ]
      }
    },
    "/payments/v2/direct-debits": {
      "post": {
        "summary": "Create direct debit",
        "description": "Create a direct debit payment.",
        "tags": [
          "Direct Debits"
        ],
        "security": [
          {
            "basicAuth": [
              "direct_debits:create",
              "accounts:read",
              "external_accounts:read",
              "counterparties:read"
            ]
          }
        ]
      },
      "get": {
        "summary": "List direct debits",
        "description": "Returns a list of direct debits. For further details on Pagination, see general section above. Sort order is always descending on date.",
        "tags": [
          "Direct Debits"
        ],
        "security": [
          {
            "basicAuth": [
              "direct_debits:read"
            ]
          }
        ]
      }
    },
    "/payments/v2/direct-debits/{id}": {
      "get": {
        "summary": "Get direct debit",
        "description": "Retrieve a specific direct debit.",
        "tags": [
          "Direct Debits"
        ],
        "security": [
          {
            "basicAuth": [
              "direct_debits:read"
            ]
          }
        ]
      }
    },
    "/payments/v2/direct-debits/{id}/events": {
      "get": {
        "summary": "List direct debit events",
        "description": "Retrieve events for a specific direct debit. Returns a list of events. For further details on Pagination, see the section above.",
        "tags": [
          "Direct Debits"
        ],
        "security": [
          {
            "basicAuth": [
              "direct_debits:read"
            ]
          }
        ]
      }
    },
    "/payments/v2/direct-debits/{id}:approve": {
      "post": {
        "summary": "Approve direct debit",
        "description": "Approve the specified direct debit.",
        "tags": [
          "Direct Debits"
        ],
        "security": [
          {
            "basicAuth": [
              "direct_debits:update"
            ]
          }
        ]
      }
    },
    "/payments/v2/direct-debits/{id}:reject": {
      "post": {
        "summary": "Reject direct debit",
        "description": "Reject the specified direct debit.",
        "tags": [
          "Direct Debits"
        ],
        "security": [
          {
            "basicAuth": [
              "direct_debits:update"
            ]
          }
        ]
      }
    },
    "/payments/v2/external-accounts/{id}": {
      "get": {
        "summary": "Get external account",
        "description": "Retrieve a specific external account.",
        "tags": [
          "External Accounts"
        ],
        "security": [
          {
            "basicAuth": [
              "external_accounts:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update external account",
        "description": "Update external account.",
        "tags": [
          "External Accounts"
        ],
        "security": [
          {
            "basicAuth": [
              "external_accounts:update"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete external account",
        "description": "Deletes the specified external account.",
        "tags": [
          "External Accounts"
        ],
        "security": [
          {
            "basicAuth": [
              "external_accounts:delete"
            ]
          }
        ]
      }
    },
    "/payments/v2/external-accounts": {
      "post": {
        "summary": "Create external account",
        "description": "Create an external account associated with a Counterparty. A maximum of 10 accounts can be created per counterparty.",
        "tags": [
          "External Accounts"
        ],
        "security": [
          {
            "basicAuth": [
              "external_accounts:create"
            ]
          }
        ]
      },
      "get": {
        "summary": "List external accounts",
        "description": "Returns a list of external accounts. For further details on Pagination, see general section above.",
        "tags": [
          "External Accounts"
        ],
        "security": [
          {
            "basicAuth": [
              "external_accounts:read"
            ]
          }
        ]
      }
    },
    "/payments/v2/counterparties": {
      "post": {
        "summary": "Create counterparty",
        "description": "Create a new counterparty.",
        "tags": [
          "Counterparties"
        ],
        "security": [
          {
            "basicAuth": [
              "counterparties:create"
            ]
          }
        ]
      },
      "get": {
        "summary": "List counterparties",
        "description": "Returns a list of counterparties. For further details on Pagination, see general section above.",
        "tags": [
          "Counterparties"
        ],
        "security": [
          {
            "basicAuth": [
              "counterparties:read"
            ]
          }
        ]
      }
    },
    "/payments/v2/counterparties/{id}": {
      "get": {
        "summary": "Get counterparty",
        "description": "Retrieve a specific counterparty.",
        "tags": [
          "Counterparties"
        ],
        "security": [
          {
            "basicAuth": [
              "counterparties:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update counterparty",
        "description": "Update a counterparty.",
        "tags": [
          "Counterparties"
        ],
        "security": [
          {
            "basicAuth": [
              "counterparties:update"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete counterparty",
        "description": "Deletes the specified counterparty.",
        "tags": [
          "Counterparties"
        ],
        "security": [
          {
            "basicAuth": [
              "counterparties:delete",
              "external_accounts:delete"
            ]
          }
        ]
      }
    },
    "/payments/v2/mandates": {
      "post": {
        "summary": "Create mandate",
        "description": "Create a new direct debit mandate.",
        "tags": [
          "Mandates"
        ],
        "security": [
          {
            "basicAuth": [
              "mandates:create",
              "external_accounts:read",
              "counterparties:read"
            ]
          }
        ]
      },
      "get": {
        "summary": "List mandates",
        "description": "Returns a list of mandates. For further details on Pagination, see general section above.",
        "tags": [
          "Mandates"
        ],
        "security": [
          {
            "basicAuth": [
              "mandates:read"
            ]
          }
        ]
      }
    },
    "/payments/v2/mandates/{id}": {
      "get": {
        "summary": "Get mandate",
        "description": "Retrieve a specific mandate.",
        "tags": [
          "Mandates"
        ],
        "security": [
          {
            "basicAuth": [
              "mandates:read"
            ]
          }
        ]
      }
    },
    "/payments/v2/mandates/{id}/events": {
      "get": {
        "summary": "List mandate events",
        "description": "Retrieve events for a specific mandate. Returns a list of events. For further details on Pagination, see the section above.",
        "tags": [
          "Mandates"
        ],
        "security": [
          {
            "basicAuth": [
              "mandates:read"
            ]
          }
        ]
      }
    },
    "/payments/v2/mandates/{id}:cancel": {
      "post": {
        "summary": "Cancel mandate",
        "description": "Cancel a specific mandate.",
        "tags": [
          "Mandates"
        ],
        "security": [
          {
            "basicAuth": [
              "mandates:update"
            ]
          }
        ]
      }
    },
    "/financial-data/v2/accounts/{id}": {
      "get": {
        "summary": "Get account",
        "description": "Retrieve a specific account.",
        "tags": [
          "Accounts"
        ],
        "security": [
          {
            "basicAuth": [
              "accounts:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update account",
        "description": "Update an account.",
        "tags": [
          "Accounts"
        ],
        "security": [
          {
            "basicAuth": [
              "accounts:update"
            ]
          }
        ]
      }
    },
    "/financial-data/v2/accounts": {
      "get": {
        "summary": "List accounts",
        "description": "Returns a list of accounts. For further details on Pagination, see general section above.",
        "tags": [
          "Accounts"
        ],
        "security": [
          {
            "basicAuth": [
              "accounts:read"
            ]
          }
        ]
      }
    },
    "/financial-data/v2/transactions": {
      "get": {
        "summary": "List transactions",
        "description": "Returns a list of transactions. For further details on Pagination, see general section above.",
        "tags": [
          "Transactions"
        ],
        "security": [
          {
            "basicAuth": [
              "transactions:read"
            ]
          }
        ]
      }
    },
    "/financial-data/v2/transactions/{id}": {
      "get": {
        "summary": "Get transaction",
        "description": "Retrieve a specific transaction.",
        "tags": [
          "Transactions"
        ],
        "security": [
          {
            "basicAuth": [
              "transactions:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update transaction",
        "description": "Update a transaction.",
        "tags": [
          "Transactions"
        ],
        "security": [
          {
            "basicAuth": [
              "transactions:update"
            ]
          }
        ]
      }
    },
    "/financial-data/v2/pending-transactions": {
      "get": {
        "summary": "List pending transactions",
        "description": "Returns a list of pending transactions. For further details on Pagination, see general section above.",
        "tags": [
          "Pending Transactions"
        ],
        "security": [
          {
            "basicAuth": [
              "pending_transactions:read"
            ]
          }
        ]
      }
    },
    "/financial-data/v2/pending-transactions/{id}": {
      "get": {
        "summary": "Get transaction",
        "description": "Retrieve a specific pending transaction.",
        "tags": [
          "Pending Transactions"
        ],
        "security": [
          {
            "basicAuth": [
              "pending_transactions:read"
            ]
          }
        ]
      }
    },
    "/financial-data/v2/pending-transactions/{id}/events": {
      "get": {
        "summary": "List pending transaction events",
        "description": "Retrieve events for a specific pending transaction. Returns a list of events. For further details on Pagination, see the section above.",
        "tags": [
          "Pending Transactions"
        ],
        "security": [
          {
            "basicAuth": [
              "pending_transactions:read"
            ]
          }
        ]
      }
    },
    "/financial-data/v2/accounts/{id}/balances": {
      "get": {
        "summary": "List balances",
        "description": "Returns a list of account balances. For further details on Pagination, see general section above.",
        "tags": [
          "Accounts"
        ],
        "security": [
          {
            "basicAuth": [
              "accounts:read",
              "account_balances:read"
            ]
          }
        ]
      }
    },
    "/financial-data/v2/entities": {
      "post": {
        "summary": "Create entity",
        "description": "Create entity.",
        "tags": [
          "Entities"
        ],
        "security": [
          {
            "basicAuth": [
              "entities:create"
            ]
          }
        ]
      },
      "get": {
        "summary": "List entities",
        "description": "Returns a list of entities. For further details on Pagination, see general section above.",
        "tags": [
          "Entities"
        ],
        "security": [
          {
            "basicAuth": [
              "entities:read"
            ]
          }
        ]
      }
    },
    "/financial-data/v2/entities/{id}": {
      "get": {
        "summary": "Get entity",
        "description": "Retrieve a specific entity.",
        "tags": [
          "Entities"
        ],
        "security": [
          {
            "basicAuth": [
              "entities:read"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete entity",
        "description": "Deletes the specified entity. It is only possible to delete an entity if it has no children or has no associated accounts.",
        "tags": [
          "Entities"
        ],
        "security": [
          {
            "basicAuth": [
              "entities:delete"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update entity",
        "description": "Update an entity.",
        "tags": [
          "Entities"
        ],
        "security": [
          {
            "basicAuth": [
              "entities:update"
            ]
          }
        ]
      }
    },
    "/iam/v2beta/oauth2/token": {
      "post": {
        "summary": "Create OAuth 2.0 access token",
        "description": "This endpoint is an OAuth 2.0 <a href=\"https://datatracker.ietf.org/doc/html/rfc6749#section-3.2\">token endpoint</a> and can be used by a client to obtain an access token.\n\nUse <a href=\"https://app.atlar.com/users/all\">programmatic access user</a> credentials as OAuth 2.0 client credentials.\nUse the <i>access key</i> as <a href=\"https://datatracker.ietf.org/doc/html/rfc6749#section-2.2\">client identifier (`client_id`)</a>.\nUse the <i>secret</i> as <a href=\"http[...]",
        "security": [
          {
            "basicAuth": []
          }
        ],
        "tags": [
          "OAuth"
        ]
      }
    }
  },
  "webhooks": {
    "resourceEvent": {
      "post": {
        "summary": "Resource event",
        "description": "Resource event delivered as a webhook request.",
        "security": [],
        "tags": [
          "Events (webhooks)"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "basicAuth": {
        "type": "http",
        "scheme": "basic"
      }
    }
  },
  "x-tagGroups": [
    {
      "name": "Payments",
      "tags": [
        "Credit Transfers",
        "Direct Debits",
        "External Accounts",
        "Counterparties",
        "Mandates",
        "Events (webhooks)",
        "Approval Chains",
        "Payment Conditions",
        "Payment Templates"
      ],
      "description": "The Payments API provides functionality for processing payments and handling payment-related operations."
    },
    {
      "name": "Financial Data",
      "tags": [
        "Accounts",
        "Transactions",
        "Pending Transactions",
        "Entities"
      ],
      "description": "The Financial Data API provides access to bank account data, e.g. account balances and account transactions."
    },
    {
      "name": "IAM",
      "tags": [
        "Identity Providers",
        "Roles",
        "Authentication",
        "Users",
        "Organizations",
        "Change Requests",
        "OAuth",
        "Invitations"
      ],
      "description": "The IAM API provides endpoints for managing identity providers and roles."
    }
  ]
}