// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetadataGroupIn metadata group in
//
// swagger:model MetadataGroupIn
type MetadataGroupIn struct {

	// key
	Key string `json:"key,omitempty"`

	// value in
	ValueIn []string `json:"valueIn"`
}

// Validate validates this metadata group in
func (m *MetadataGroupIn) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this metadata group in based on context it is used
func (m *MetadataGroupIn) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetadataGroupIn) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetadataGroupIn) UnmarshalBinary(b []byte) error {
	var res MetadataGroupIn
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
