// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WebAuthnChallenge web authn challenge
//
// swagger:model WebAuthnChallenge
type WebAuthnChallenge struct {

	// credential assertion
	CredentialAssertion string `json:"credentialAssertion,omitempty"`

	// session Id
	SessionID string `json:"sessionId,omitempty"`
}

// Validate validates this web authn challenge
func (m *WebAuthnChallenge) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this web authn challenge based on context it is used
func (m *WebAuthnChallenge) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WebAuthnChallenge) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebAuthnChallenge) UnmarshalBinary(b []byte) error {
	var res WebAuthnChallenge
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
