// Code generated by go-swagger; DO NOT EDIT.

package expected_transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostV1betaExpectedTransactionsIDUnarchiveParams creates a new PostV1betaExpectedTransactionsIDUnarchiveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1betaExpectedTransactionsIDUnarchiveParams() *PostV1betaExpectedTransactionsIDUnarchiveParams {
	return &PostV1betaExpectedTransactionsIDUnarchiveParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1betaExpectedTransactionsIDUnarchiveParamsWithTimeout creates a new PostV1betaExpectedTransactionsIDUnarchiveParams object
// with the ability to set a timeout on a request.
func NewPostV1betaExpectedTransactionsIDUnarchiveParamsWithTimeout(timeout time.Duration) *PostV1betaExpectedTransactionsIDUnarchiveParams {
	return &PostV1betaExpectedTransactionsIDUnarchiveParams{
		timeout: timeout,
	}
}

// NewPostV1betaExpectedTransactionsIDUnarchiveParamsWithContext creates a new PostV1betaExpectedTransactionsIDUnarchiveParams object
// with the ability to set a context for a request.
func NewPostV1betaExpectedTransactionsIDUnarchiveParamsWithContext(ctx context.Context) *PostV1betaExpectedTransactionsIDUnarchiveParams {
	return &PostV1betaExpectedTransactionsIDUnarchiveParams{
		Context: ctx,
	}
}

// NewPostV1betaExpectedTransactionsIDUnarchiveParamsWithHTTPClient creates a new PostV1betaExpectedTransactionsIDUnarchiveParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1betaExpectedTransactionsIDUnarchiveParamsWithHTTPClient(client *http.Client) *PostV1betaExpectedTransactionsIDUnarchiveParams {
	return &PostV1betaExpectedTransactionsIDUnarchiveParams{
		HTTPClient: client,
	}
}

/*
PostV1betaExpectedTransactionsIDUnarchiveParams contains all the parameters to send to the API endpoint

	for the post v1beta expected transactions ID unarchive operation.

	Typically these are written to a http.Request.
*/
type PostV1betaExpectedTransactionsIDUnarchiveParams struct {

	/* ID.

	   Expected Transaction ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1beta expected transactions ID unarchive params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1betaExpectedTransactionsIDUnarchiveParams) WithDefaults() *PostV1betaExpectedTransactionsIDUnarchiveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1beta expected transactions ID unarchive params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1betaExpectedTransactionsIDUnarchiveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1beta expected transactions ID unarchive params
func (o *PostV1betaExpectedTransactionsIDUnarchiveParams) WithTimeout(timeout time.Duration) *PostV1betaExpectedTransactionsIDUnarchiveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1beta expected transactions ID unarchive params
func (o *PostV1betaExpectedTransactionsIDUnarchiveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1beta expected transactions ID unarchive params
func (o *PostV1betaExpectedTransactionsIDUnarchiveParams) WithContext(ctx context.Context) *PostV1betaExpectedTransactionsIDUnarchiveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1beta expected transactions ID unarchive params
func (o *PostV1betaExpectedTransactionsIDUnarchiveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1beta expected transactions ID unarchive params
func (o *PostV1betaExpectedTransactionsIDUnarchiveParams) WithHTTPClient(client *http.Client) *PostV1betaExpectedTransactionsIDUnarchiveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1beta expected transactions ID unarchive params
func (o *PostV1betaExpectedTransactionsIDUnarchiveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post v1beta expected transactions ID unarchive params
func (o *PostV1betaExpectedTransactionsIDUnarchiveParams) WithID(id string) *PostV1betaExpectedTransactionsIDUnarchiveParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post v1beta expected transactions ID unarchive params
func (o *PostV1betaExpectedTransactionsIDUnarchiveParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1betaExpectedTransactionsIDUnarchiveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
